# app/config/security.yml
security:
    encoders:
        Senna\Bundle\AppBundle\Model\User: sha512

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN]

    providers:
        senna_userbundle:
            id: senna.user.user_provider.username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            form_login:
                check_path: login_check
                provider: senna_userbundle
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/node, role: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/*, role: ROLE_USER }
