login:
    path: /login
    defaults: { _controller: "SennaAppBundle:Security:login" }

login_check:
    path: /login_check
    defaults: { _controller: "SennaAppBundle:Security:check" }

user_logout:
    path: /logout
    defaults: { _controller: "SennaAppBundle:Security:logout" }


dashboard:
    path: /
    defaults: { _controller: "SennaAppBundle:Dashboard:main" }

settings:
    path: /settings
    defaults:
        _controller: "sylius.controller.settings:updateAction"
        namespace: general
        template: SennaAppBundle:Settings:update.html.twig


rooms:
    path: /rooms
    defaults:
        _controller: "senna.controller.room:indexAction"
        _sylius:
            template: SennaAppBundle:Room:index.html.twig

room_create:
    path: /room/create
    defaults:
        _controller: "senna.controller.room:createAction"
        _sylius:
            form: Senna\Bundle\AppBundle\Form\Type\RoomType
            template: SennaAppBundle:Room:create.html.twig
            redirect: rooms

node_register:
    path: /node/register
    defaults:
        _controller: senna.controller.node:registerAction

nodes:
    path: /nodes
    defaults:
        _controller: "senna.controller.node:indexAction"
        _sylius:
            template: SennaAppBundle:Node:index.html.twig

node_data:
    path: /node/{id}/data
    defaults:
        _controller: "senna.controller.node:dataAction"
        _sylius:
            template: SennaAppBundle:Node:data.html.twig

node_create:
    path: /node/create
    defaults:
        _controller: "senna.controller.node:createAction"
        _sylius:
            template: SennaAppBundle:Node:create.html.twig
            form: Senna\Bundle\AppBundle\Form\Type\NodeType
            redirect: rooms


logs:
    path: /logs
    defaults:
        _controller: "senna.controller.log:indexAction"
        _sylius:
            template: SennaAppBundle:Log:index.html.twig


log_create:
    path: /api/logs/add
    defaults:
        _controller: "senna.controller.log:createAction"
